### PR TITLE
Feature: Add Rails 5+ support

### PR DESCRIPTION
**Pull request by mufudzimasaire**
PR adds support for Rails 5+ 

Addresses Issues: https://github.com/luisalima/outdatedbrowser_rails/issues/8 https://github.com/luisalima/outdatedbrowser_rails/issues/9

### CODE REVIEW

**Comment by luisalima** [comment]
Perfect! Thank you for the contribution @mufudzimasaire 👍

**Comment by mufudzimasaire** [comment]
Not a problem @luisalima :). Can we please create a release for `v1.1.4`?

**Comment by luisalima** [comment]
@mufudzimasaire thank you so much for your help, apologies for the delay, I have been sick and only got around to this now! It's created and published to Rubygems. 👍

**Comment by mufudzimasaire** [comment]
Not a problem @luisalima, thanks for that 👍

**Pull request merged**
