### PR TITLE
Update to Rails 4

### PR DESCRIPTION
**Pull request by nhodges**

### CODE REVIEW

**Comment by luisalima** [comment]
@nhodges please fix the tests so that you don't include `spec/dummy/app/assets/javascripts/outdatedbrowser/outdatedbrowser.js` and `spec/dummy/app/assets/stylesheets/outdatedbrowser/outdatedbrowser.css`, otherwise you're testing the inclusion of those files and not the gem's files.

After that, I'll merge. Thanks for the PR! :+1:

**Comment by zedtux** [comment]
@nhodges any chance you update your branch soon ?

**Comment by nhodges** [comment]
I'll try to update the branch today. It's actually by @sqlninja so I will have to fork and take a look at the specs.

**Comment by sqlninja** [comment]
I will gladly pull in any needed changes to this branch to facilitate a merge into the base branch...

**Comment by zedtux** [comment]
Thank you both :)

**Comment by luisalima** [comment]
This was fixed in #5, so I'll close this PR. Thanks for the reminder for giving some :heart: to this gem, @nhodges, @sqlninja and @zedtux . I had lots of stuff going on, and with all the emails I stopped watching `outdatedbrowser`. As such, I hadn't updated the gem as I should. I'm watching the `outdatedbrowser` repo again :wink: 
 
* To update `outdatedbrowser`, and just to make sure that contributors know what they need to do, I'll add a "how to contribute" to the README. Basically, `outdatedbrowser` files are in a git submodule, which needs to be updated for updating the gem. Afterwards, you need to run `rake clean` (which basically erases the "old" outdatedbrowser files from `app/assets`) and `rake generate:assets` (which basically copies the assets from the outdatedbrowser vendor submodule to `app/assets` again).
@zedtux reminded me that I should align the gem versions with the library versions (which they already were, by the way, the outdadedbrowser version just hadn't been updated in a loong time...) and that I should tag the version, which I had forgotten about :+1: 

Would this be enough to make it clearer for you guys?

In the future, if any of you guys want to contribute, I'll gladly accept help, and I'm sure that @alexprg will also appreciate having extra people looking after this gem, since he references it in the README of `outdatedbrowser`.

Please let me know if there is any problem with #5 . I was actively using this gem in a rails project, but I dropped that project so I'm not "eating my own dog food" anymore.

@nhodges if you'd like to take a look at how to test a rails engine properly, please check [the rails guides on engines](http://edgeguides.rubyonrails.org/engines.html) and drop me a line if you still have questions.

**Comment by zedtux** [comment]
Awesome @luisalima, thank you.

A side note, the git submodule doesn't look efficient and it sounds easier to me to have a script downloading files for a given version (here aligning with the lib's version helps, as you can fetch the gem version and download the files for that version).

As of now, I'm not using this gem because of an issue in the lib itself. It lakes of cookie management in order to show only once the modal, so I have manually downloaded the files and updated the script with the cookie management.

**Comment by luisalima** [comment]
@zedtux I actually like the git submodule approach if there aren't lots of new versions popping up :smile: It marks _exactly_ the commit from where those files come, so if, for example, the gem owner forgot to tag the release _cof cof_ then we can still know exactly where the files came from :blush: But thanks for the idea!

I'm not sure that cookie management should come with `outdatedbrowser` itself, because cookies have other implications (like the mandatory EU warning...). I guess it's their call. If you'd like to PR for optional cookie support within this repo, I'll gladly look at it and help you out :smile:

**Comment by zedtux** [comment]
> If you'd like to PR for optional cookie support within this repo, I'll gladly look at it and help you out

Well this needs to be done in the library itself, not in the warping gem but thank you :)

**Comment by luisalima** [comment]
@zedtux true... :smile: maybe you can PR your work into `outdatedbrowser`! Let me know if there is any more way that I can help :smile:

**Comment by sqlninja** [comment]
I think cookie management should be left to developers consuming the gem
and showing the message. The use of cookies assumes a lot upon the
developers...

**Pull request closed without merging**
