### PR TITLE
Add Rails ~> 6 support

### PR DESCRIPTION
**Pull request by mzishtiaq**
This PR adds rails ~>6 support.

### CODE REVIEW

**Comment by mzishtiaq** [comment]
Hey @luisalima. 👋  😄

**Comment by gr8bit** [comment]
@mzishtiaq we should probably all be using this instead of the original outdatedbrowser anyway...
https://github.com/mikemaccana/outdated-browser-rework#readme

**Comment by luisalima** [comment]
Thanks @mzishtiaq , apologies, my inbox was swamped and I somehow missed this!
@gr8bit thanks for the reference to outdated-browser-rework , didn't know it yet 👍

**Comment by gr8bit** [comment]
@luisalima Thank you for the merge! Could you publish a new gem as well or should I point my Gemfile to the repo for now?

**Comment by mzishtiaq** [comment]
@luisalima That's not a problem at all. Thank you!

**Comment by mzishtiaq** [comment]
> @mzishtiaq we should probably all be using this instead of the original outdatedbrowser anyway...
> https://github.com/mikemaccana/outdated-browser-rework#readme

You're right! I will see if I can find some time and update this gem so everyone can benefit from it. :)

**Comment by luisalima** [comment]
@mzishtiaq Just did! Thank you for your help 💙

**Pull request merged**
